package domain

import "errors"

var (
	ErrNotFound                    = errors.New("not found")
	ErrDuplicateEmail              = errors.New("email already registered")
	ErrInvalidToken                = errors.New("invalid or expired token")
	ErrInvalidPassword             = errors.New("invalid email or password")
	ErrAccountSuspended            = errors.New("account is suspended")
	ErrAccountLocked               = errors.New("account temporarily locked")
	ErrTOTPRequired                = errors.New("2FA verification required")
	ErrTOTPInvalid                 = errors.New("invalid TOTP code")
	ErrTOTPAlreadyOn               = errors.New("TOTP already enabled")
	ErrTOTPNotEnabled              = errors.New("TOTP not enabled")
	ErrTOTPNoPending               = errors.New("no TOTP setup pending")
	ErrRedisRequired               = errors.New("this feature requires Redis")
	ErrEmailNotConfigured          = errors.New("email sending not configured")
	ErrRateLimit                   = errors.New("too many requests, try again later")
	ErrWeakPassword                = errors.New("password does not meet strength requirements")
	ErrEmailAlreadyVerified        = errors.New("email already verified")
	ErrInvalidClient               = errors.New("invalid API key")
	ErrClientSuspended             = errors.New("client is suspended")
	ErrForbidden                   = errors.New("forbidden")
	ErrInvalidRequest              = errors.New("invalid request")
	ErrDuplicateOrganization       = errors.New("organization already exists")
	ErrDuplicateMembership         = errors.New("organization membership already exists")
	ErrInvalidRole                 = errors.New("invalid organization role")
	ErrInvalidPermission           = errors.New("invalid organization permission")
	ErrInvalidAuthorizationPolicy  = errors.New("invalid authorization policy")
	ErrAuthorizationPolicyConflict = errors.New("authorization policy version conflict")
	ErrInvalidGroupMapping         = errors.New("invalid organization group mapping")
	ErrInvalidInvitation           = errors.New("invalid organization invitation")
	ErrInvitationExpired           = errors.New("organization invitation expired")
	ErrInvalidScope                = errors.New("invalid scope")
	ErrInvalidClientCredentials    = errors.New("invalid client credentials")
	ErrInvalidSSOConnection        = errors.New("invalid enterprise sso connection")
	ErrSSODomainNotAllowed         = errors.New("email domain is not allowed for this sso connection")
	ErrSSORequired                 = errors.New("enterprise sso is required for this email domain")
	ErrInvalidSCIMToken            = errors.New("invalid scim token")
	ErrInvalidSCIMResource         = errors.New("invalid scim resource")
	ErrPasskeyAttestation          = errors.New("passkey attestation rejected")
	ErrBotVerification             = errors.New("bot verification failed")
	ErrMFARequired                 = errors.New("admin MFA verification required")
	ErrMFAEnrollmentRequired       = errors.New("admin MFA enrollment required")
	ErrInvalidAdminToken           = errors.New("invalid or expired admin token")
	ErrInvalidAdminRole            = errors.New("invalid admin role")
	ErrInvalidAdminScope           = errors.New("invalid admin scope")
	ErrAdminPermissionDenied       = errors.New("admin permission denied")
	ErrStepUpRequired              = errors.New("step-up verification required")
	ErrStepUpEnrollmentRequired    = errors.New("step-up factor enrollment required")
	ErrSecurityPolicyBlocked       = errors.New("blocked by adaptive security policy")
)
